services:
  postgres-property-management:
    image: postgres:16-alpine
    container_name: booking-postgres-property-management
    restart: always
    environment:
      POSTGRES_DB: property_db
      POSTGRES_USER: property_user
      POSTGRES_PASSWORD: property_pass
    ports:
      - "5434:5432"
    volumes:
      - postgres-property-management-data:/var/lib/postgresql/data
    networks:
      - booking-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U property_user -d property_db"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  booking-network:
    driver: bridge

volumes:
  postgres-property-management-data: